/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.CarDetails;
import Model.CarHistory;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author swathisharma
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    CarHistory history;
    
    public CreateJPanel(CarHistory history) {
        initComponents();
        
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblcarMake = new javax.swing.JLabel();
        lblCarModel = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblCarSerial = new javax.swing.JLabel();
        lblNumSeats = new javax.swing.JLabel();
        lblRegDate = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtCarMake = new javax.swing.JTextField();
        txtCarModel = new javax.swing.JTextField();
        txtSerialNum = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtNumSeats = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        txtRegDate = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        lblcertExpiry = new javax.swing.JLabel();
        chkBoxAvailable = new java.awt.Checkbox();
        chkBoxExpiry = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        lblcarmodelvali = new javax.swing.JLabel();
        lblcarmodelnumvali = new javax.swing.JLabel();
        lblserialnumvali = new javax.swing.JLabel();
        lblregistdatevali = new javax.swing.JLabel();
        lblnoofseats = new javax.swing.JLabel();
        lblmanuyear = new javax.swing.JLabel();
        lblregisvali = new javax.swing.JLabel();
        lblcityvali = new javax.swing.JLabel();
        lblyearvali = new javax.swing.JLabel();
        lblnoofseatsvali = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setFont(new java.awt.Font("Muna", 0, 13)); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));

        lblcarMake.setText("Car Model");

        lblCarModel.setText("Car Model Number");

        lblYear.setText("Manufacture Year");

        lblCarSerial.setText("Car Serial Number");

        lblNumSeats.setText("Number of Seats");

        lblRegDate.setText("Registration Date");

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });

        txtCarMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarMakeActionPerformed(evt);
            }
        });
        txtCarMake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarMakeKeyPressed(evt);
            }
        });

        txtCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarModelActionPerformed(evt);
            }
        });
        txtCarModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarModelKeyPressed(evt);
            }
        });

        txtSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumActionPerformed(evt);
            }
        });
        txtSerialNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerialNumKeyPressed(evt);
            }
        });

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearKeyPressed(evt);
            }
        });

        txtNumSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumSeatsKeyPressed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblCity.setText("City");

        txtRegDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegDateActionPerformed(evt);
            }
        });
        txtRegDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRegDateKeyPressed(evt);
            }
        });

        lblAvailability.setText("Availability (Yes/No)");

        lblcertExpiry.setText("Certificate Expiry (Yes/No)");

        chkBoxAvailable.setLabel("YES");

        chkBoxExpiry.setLabel("YES");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        titleLabel.setFont(new java.awt.Font("Sinhala MN", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("CREATE CAR DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcarMake)
                            .addComponent(lblCarModel)
                            .addComponent(lblCarSerial)
                            .addComponent(lblYear)
                            .addComponent(lblNumSeats)
                            .addComponent(lblRegDate)
                            .addComponent(lblCity)
                            .addComponent(lblAvailability)
                            .addComponent(lblcertExpiry))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(txtSerialNum, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(txtCarModel, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(txtCarMake, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtRegDate, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(chkBoxAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCity)
                            .addComponent(chkBoxExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblcarmodelvali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblcarmodelnumvali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblserialnumvali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblregistdatevali)
                                .addGap(5, 5, 5)
                                .addComponent(lblregisvali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblcityvali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblyearvali)
                                    .addComponent(lblmanuyear)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnoofseatsvali)
                                    .addComponent(lblnoofseats))))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCarMake, txtCarModel, txtCity, txtNumSeats, txtRegDate, txtSerialNum, txtYear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblcarMake)
                                    .addComponent(txtCarMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcarmodelvali))
                                .addGap(23, 23, 23)
                                .addComponent(lblCarModel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblcarmodelnumvali)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarSerial)
                            .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblserialnumvali))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblYear)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblyearvali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmanuyear)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumSeats)
                            .addComponent(txtNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnoofseats)
                            .addComponent(lblnoofseatsvali))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegDate)
                            .addComponent(txtRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblregistdatevali)
                            .addComponent(lblregisvali))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCity)
                        .addComponent(lblcityvali)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkBoxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailability))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcertExpiry)
                    .addComponent(chkBoxExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCarMake, txtCarModel, txtCity, txtNumSeats, txtSerialNum, txtYear});

    }// </editor-fold>//GEN-END:initComponents

    private void txtCarMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarMakeActionPerformed
        // TODO add your handling code here:
        
       
        
        
        
    }//GEN-LAST:event_txtCarMakeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        int year = Integer.parseInt(txtYear.getText());
        int numOfSeats = Integer.parseInt(txtNumSeats.getText());
        String RegDate  = txtRegDate.getText();
        String CarMake  = txtCarMake.getText();
        String ModelNum  = txtCarModel.getText();
        String SerialNum  = txtSerialNum.getText();
        String City  = txtCity.getText();
        Boolean Availability = chkBoxAvailable.getState();
        Boolean Expiry = chkBoxExpiry.getState();

        CarDetails cd = history.addNewCar();
        
        cd.setCarModel(CarMake);
        cd.setCarModelNumber(ModelNum);
        cd.setCarSerialNumber(SerialNum);
        cd.setNumOfSeats(numOfSeats);
        cd.setRegDate(RegDate);
        cd.setCity(City);

        cd.setYear(year);
        cd.setAvailability(Availability);
        cd.setExpiry(Expiry);
        
        JOptionPane.showMessageDialog(this, "New Car Detail is created");
        
        txtYear.setText("");
        txtNumSeats.setText("");
        txtCity.setText("");
        txtRegDate.setText("");
        txtCarMake.setText("");
        txtCarModel.setText("");
        txtSerialNum.setText("");
        chkBoxAvailable.setState(false);
        chkBoxExpiry.setState(false);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarModelActionPerformed
        // TODO add your handling code here:
        
        
                
            
    }//GEN-LAST:event_txtCarModelActionPerformed
    
    private void txtSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumActionPerformed
        // TODO add your handling code here:
        
     //String serialnum=txtSerialNum.getText();
        //get length of a string
        //int length =serialnum.length();
        
       // char c = evt.getKeyChar();
        
        //Check for number 0-9
        
       // if(evt.getKeyChar()>='0' && evt.getKeyChar()<='4'){
            //if (length<5){
                //editable true
               // txtSerialNum.setEditable(true);
               /// lblserialnumvali.setText("Please enter CAR Model number only!");
            //}else{
                //not editable for length more than 10 digits 
               // txtSerialNum.setEditable(false);
                //lblserialnumvali.setText("");
               
        
    }//GEN-LAST:event_txtSerialNumActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtRegDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegDateActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_txtRegDateActionPerformed

    private void txtCarMakeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarMakeKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            txtCarMake.setEditable(false);
            lblcarmodelvali.setText("Please Car Model only!");
        }
        else
        {
            txtCarMake.setEditable(true);
            lblcarmodelvali.setText(""); // To disable the warnings once user feed correct character
        }
    }//GEN-LAST:event_txtCarMakeKeyPressed

    private void txtCarModelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarModelKeyPressed
        // TODO add your handling code here:
        
        String CarModel=txtCarModel.getText();
        //get length of a string
        int length =CarModel.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='4'){
            if (length<5){
                //editable true
                txtCarModel.setEditable(true);
                lblcarmodelnumvali.setText("Please enter Car Model  Number only!");
            }else{
                //not editable for length more than 10 digits 
                txtCarModel.setEditable(false);
                lblcarmodelnumvali.setText("");
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtCarModel.setEditable(true);
                
            }else{
                txtCarModel.setEditable(false);
            }
                
            
           }
    }//GEN-LAST:event_txtCarModelKeyPressed

    private void txtSerialNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumKeyPressed
        // TODO add your handling code here:
        
        String serialnum=txtSerialNum.getText();
        //get length of a string
        int length =serialnum.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='7'){
            if (length<8){
                //editable true
                txtSerialNum.setEditable(true);
                lblserialnumvali.setText("Please enter serial number only!");
            }else{
                //not editable for length more than 10 digits 
                txtSerialNum.setEditable(false);
                lblserialnumvali.setText("");
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtSerialNum.setEditable(true);
                
            }else{
                txtSerialNum.setEditable(false);
            }
                
            
           }
        
        
    }//GEN-LAST:event_txtSerialNumKeyPressed

    private void txtYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyPressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtYearKeyPressed

    private void txtNumSeatsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSeatsKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNumSeatsKeyPressed

    private void txtRegDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegDateKeyPressed
        // TODO add your handling code here:
        char MDKeyPressed = evt.getKeyChar();
        if(Character.isAlphabetic(MDKeyPressed)){
            txtRegDate.setEditable(false);
            lblregistdatevali.setText("Invalid Format, Only  MM/DD/YYYY is allowed!");
        }
        else
        {
            txtRegDate.setEditable(true);
            lblregistdatevali.setText("");
        }
       
        
        
    }//GEN-LAST:event_txtRegDateKeyPressed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            txtCity.setEditable(false);
            lblcityvali.setText("Please enter City Details only!");
        }
        else
        {
            txtCity.setEditable(true);
            lblcityvali.setText(""); // To disable the warnings once user feed correct character
        }
    }//GEN-LAST:event_txtCityKeyPressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Checkbox chkBoxAvailable;
    private java.awt.Checkbox chkBoxExpiry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCarSerial;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblNumSeats;
    private javax.swing.JLabel lblRegDate;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblcarMake;
    private javax.swing.JLabel lblcarmodelnumvali;
    private javax.swing.JLabel lblcarmodelvali;
    private javax.swing.JLabel lblcertExpiry;
    private javax.swing.JLabel lblcityvali;
    private javax.swing.JLabel lblmanuyear;
    private javax.swing.JLabel lblnoofseats;
    private javax.swing.JLabel lblnoofseatsvali;
    private javax.swing.JLabel lblregistdatevali;
    private javax.swing.JLabel lblregisvali;
    private javax.swing.JLabel lblserialnumvali;
    private javax.swing.JLabel lblyearvali;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField txtCarMake;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtNumSeats;
    private javax.swing.JTextField txtRegDate;
    private javax.swing.JTextField txtSerialNum;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
