/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

//import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author ankitaindi
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    
    Person person ;
    public ViewPanel(Person person) {
        initComponents();
        
        this.person=person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        JLabeltitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeographicdata = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTelephonenum = new javax.swing.JLabel();
        lblFaxnum = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblmedicalrecordnum = new javax.swing.JLabel();
        lblhealthplannumber = new javax.swing.JLabel();
        lblbankaccountnumber = new javax.swing.JLabel();
        lblLicensenumber = new javax.swing.JLabel();
        lbllicenseplate = new javax.swing.JLabel();
        lblDeviceidentifier = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblinternetprotocoladdr = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lbluniquenumber = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        textgeographicData = new javax.swing.JTextField();
        textdoB = new javax.swing.JTextField();
        texttelephonenum = new javax.swing.JTextField();
        textfaxnumber = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        textSSN = new javax.swing.JTextField();
        textMedicalNumber = new javax.swing.JTextField();
        texthealthplan = new javax.swing.JTextField();
        textbankaccountnumber = new javax.swing.JTextField();
        textlicensenumber = new javax.swing.JTextField();
        textvehicleserialnum = new javax.swing.JTextField();
        textdeviceidentifier = new javax.swing.JTextField();
        textlinkedin = new javax.swing.JTextField();
        textprotocoladdress = new javax.swing.JTextField();
        textuniqueidentifyingnumber = new javax.swing.JTextField();
        btnBioImg = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        JLabeltitle.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        JLabeltitle.setText(" View User Profile");

        lblName.setText("Name:");

        lblGeographicdata.setText("Geographic Data:");

        lblDob.setText("Date of Birth:");

        lblTelephonenum.setText("Telephone Number:");

        lblFaxnum.setText("Fax Number:");

        lblemail.setText("Email:");

        lblSSN.setText("SSN:");

        lblmedicalrecordnum.setText("Medical Record Number:");

        lblhealthplannumber.setText("Health Plan Beneficiary Number:");

        lblbankaccountnumber.setText("Bank Account Number:");

        lblLicensenumber.setText("License Number:");

        lbllicenseplate.setText("Vehicle SerialNumber:");

        lblDeviceidentifier.setText("Device Identifier:");

        lblLinkedin.setText("LinkedIn:");

        lblinternetprotocoladdr.setText("Internet Protocol Address:");

        lblPhoto.setText("Photo:");

        lbluniquenumber.setText("Unique identifying Number:");

        texttelephonenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttelephonenumActionPerformed(evt);
            }
        });

        textfaxnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfaxnumberActionPerformed(evt);
            }
        });

        textuniqueidentifyingnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textuniqueidentifyingnumberKeyPressed(evt);
            }
        });

        btnBioImg.setText("View Photo");
        btnBioImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBioImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDob)
                    .addComponent(lblemail)
                    .addComponent(lblmedicalrecordnum)
                    .addComponent(lbllicenseplate)
                    .addComponent(lbluniquenumber)
                    .addComponent(lblPhoto)
                    .addComponent(lblinternetprotocoladdr)
                    .addComponent(lblLinkedin)
                    .addComponent(lblDeviceidentifier)
                    .addComponent(lblhealthplannumber)
                    .addComponent(lblLicensenumber)
                    .addComponent(lblbankaccountnumber)
                    .addComponent(lblSSN)
                    .addComponent(lblFaxnum)
                    .addComponent(lblTelephonenum)
                    .addComponent(lblGeographicdata)
                    .addComponent(lblName))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textprotocoladdress)
                    .addComponent(textlinkedin)
                    .addComponent(textdeviceidentifier)
                    .addComponent(textvehicleserialnum)
                    .addComponent(textlicensenumber)
                    .addComponent(textbankaccountnumber)
                    .addComponent(texthealthplan)
                    .addComponent(textMedicalNumber)
                    .addComponent(textSSN)
                    .addComponent(textemail)
                    .addComponent(textfaxnumber)
                    .addComponent(texttelephonenum)
                    .addComponent(textdoB)
                    .addComponent(textgeographicData)
                    .addComponent(textuniqueidentifyingnumber)
                    .addComponent(btnBioImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(JLabeltitle))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(JLabeltitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeographicdata)
                    .addComponent(textgeographicData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textdoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDob))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelephonenum)
                            .addComponent(texttelephonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFaxnum)
                            .addComponent(textfaxnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblemail)
                            .addComponent(textemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(textSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMedicalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmedicalrecordnum))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(texthealthplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblhealthplannumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblbankaccountnumber)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textlicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicensenumber))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicenseplate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textvehicleserialnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceidentifier)
                    .addComponent(textdeviceidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLinkedin)
                    .addComponent(textlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinternetprotocoladdr)
                    .addComponent(textprotocoladdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoto)
                    .addComponent(btnBioImg))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluniquenumber)
                    .addComponent(textuniqueidentifyingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void texttelephonenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttelephonenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttelephonenumActionPerformed

    private void textfaxnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfaxnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfaxnumberActionPerformed

    private void btnBioImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBioImgActionPerformed
        // TODO add your handling code here:
        person.getImage();
    }//GEN-LAST:event_btnBioImgActionPerformed

    private void textuniqueidentifyingnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textuniqueidentifyingnumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textuniqueidentifyingnumberKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabeltitle;
    private javax.swing.JButton btnBioImg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblDeviceidentifier;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFaxnum;
    private javax.swing.JLabel lblGeographicdata;
    private javax.swing.JLabel lblLicensenumber;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephonenum;
    private javax.swing.JLabel lblbankaccountnumber;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblhealthplannumber;
    private javax.swing.JLabel lblinternetprotocoladdr;
    private javax.swing.JLabel lbllicenseplate;
    private javax.swing.JLabel lblmedicalrecordnum;
    private javax.swing.JLabel lbluniquenumber;
    private javax.swing.JTextField textMedicalNumber;
    private javax.swing.JTextField textSSN;
    private javax.swing.JTextField textbankaccountnumber;
    private javax.swing.JTextField textdeviceidentifier;
    private javax.swing.JTextField textdoB;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textfaxnumber;
    private javax.swing.JTextField textgeographicData;
    private javax.swing.JTextField texthealthplan;
    private javax.swing.JTextField textlicensenumber;
    private javax.swing.JTextField textlinkedin;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textprotocoladdress;
    private javax.swing.JTextField texttelephonenum;
    private javax.swing.JTextField textuniqueidentifyingnumber;
    private javax.swing.JTextField textvehicleserialnum;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
        //person.setText(person.getName());
        //person.setGeographicdata(textgeographicData.getText());
        textname.setText(person.getName());
        textgeographicData.setText(person.getGeographicdata());
        textdoB.setText(person.getDob());
        texttelephonenum.setText(person.getTelephonenum());
        textfaxnumber.setText(person.getFaxnum());
        textemail.setText(person.getEmailID());
        textSSN.setText(person.getSSN());
        textMedicalNumber.setText((person.getMedicalrecordnum()));
        texthealthplan.setText((person.getHealthplannum()));
        textbankaccountnumber.setText((person.getBankaccnum()));
        textlicensenumber.setText((person.getLicensenum()));
        textdeviceidentifier.setText((person.getDeviceidentifier()));
        textlinkedin.setText(person.getLinkedin());
        textprotocoladdress.setText(person.getInternetprotocaladdr());
        textuniqueidentifyingnumber.setText(person.getUniqueidentifier());
          
         
        
    
    }

    //private void showMessageDialogue(ViewPanel aThis, String user_Information_Saved) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
